; Auto-generated. Do not edit!


(cl:in-package real_robot_control-msg)


;//! \htmlinclude screwResult.msg.html

(cl:defclass <screwResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:integer
    :initform 0))
)

(cl:defclass screwResult (<screwResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <screwResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'screwResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name real_robot_control-msg:<screwResult> is deprecated: use real_robot_control-msg:screwResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <screwResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader real_robot_control-msg:result-val is deprecated.  Use real_robot_control-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <screwResult>) ostream)
  "Serializes a message object of type '<screwResult>"
  (cl:let* ((signed (cl:slot-value msg 'result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <screwResult>) istream)
  "Deserializes a message object of type '<screwResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<screwResult>)))
  "Returns string type for a message object of type '<screwResult>"
  "real_robot_control/screwResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'screwResult)))
  "Returns string type for a message object of type 'screwResult"
  "real_robot_control/screwResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<screwResult>)))
  "Returns md5sum for a message object of type '<screwResult>"
  "034a8e20d6a306665e3a5b340fab3f09")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'screwResult)))
  "Returns md5sum for a message object of type 'screwResult"
  "034a8e20d6a306665e3a5b340fab3f09")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<screwResult>)))
  "Returns full string definition for message of type '<screwResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#最终结果~%int32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'screwResult)))
  "Returns full string definition for message of type 'screwResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#最终结果~%int32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <screwResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <screwResult>))
  "Converts a ROS message object to a list"
  (cl:list 'screwResult
    (cl:cons ':result (result msg))
))
