; Auto-generated. Do not edit!


(cl:in-package real_robot_control-msg)


;//! \htmlinclude screwFeedback.msg.html

(cl:defclass <screwFeedback> (roslisp-msg-protocol:ros-message)
  ((screw_status
    :reader screw_status
    :initarg :screw_status
    :type cl:float
    :initform 0.0))
)

(cl:defclass screwFeedback (<screwFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <screwFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'screwFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name real_robot_control-msg:<screwFeedback> is deprecated: use real_robot_control-msg:screwFeedback instead.")))

(cl:ensure-generic-function 'screw_status-val :lambda-list '(m))
(cl:defmethod screw_status-val ((m <screwFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader real_robot_control-msg:screw_status-val is deprecated.  Use real_robot_control-msg:screw_status instead.")
  (screw_status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <screwFeedback>) ostream)
  "Serializes a message object of type '<screwFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'screw_status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <screwFeedback>) istream)
  "Deserializes a message object of type '<screwFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'screw_status) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<screwFeedback>)))
  "Returns string type for a message object of type '<screwFeedback>"
  "real_robot_control/screwFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'screwFeedback)))
  "Returns string type for a message object of type 'screwFeedback"
  "real_robot_control/screwFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<screwFeedback>)))
  "Returns md5sum for a message object of type '<screwFeedback>"
  "e3afaebb6a3462d8877452e53c10c331")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'screwFeedback)))
  "Returns md5sum for a message object of type 'screwFeedback"
  "e3afaebb6a3462d8877452e53c10c331")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<screwFeedback>)))
  "Returns full string definition for message of type '<screwFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#连续反馈~%float64 screw_status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'screwFeedback)))
  "Returns full string definition for message of type 'screwFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#连续反馈~%float64 screw_status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <screwFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <screwFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'screwFeedback
    (cl:cons ':screw_status (screw_status msg))
))
