// Generated by gencpp from file real_robot_control/current_pub.msg
// DO NOT EDIT!


#ifndef REAL_ROBOT_CONTROL_MESSAGE_CURRENT_PUB_H
#define REAL_ROBOT_CONTROL_MESSAGE_CURRENT_PUB_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace real_robot_control
{
template <class ContainerAllocator>
struct current_pub_
{
  typedef current_pub_<ContainerAllocator> Type;

  current_pub_()
    : current(0.0)  {
    }
  current_pub_(const ContainerAllocator& _alloc)
    : current(0.0)  {
  (void)_alloc;
    }



   typedef double _current_type;
  _current_type current;





  typedef boost::shared_ptr< ::real_robot_control::current_pub_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::real_robot_control::current_pub_<ContainerAllocator> const> ConstPtr;

}; // struct current_pub_

typedef ::real_robot_control::current_pub_<std::allocator<void> > current_pub;

typedef boost::shared_ptr< ::real_robot_control::current_pub > current_pubPtr;
typedef boost::shared_ptr< ::real_robot_control::current_pub const> current_pubConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::real_robot_control::current_pub_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::real_robot_control::current_pub_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::real_robot_control::current_pub_<ContainerAllocator1> & lhs, const ::real_robot_control::current_pub_<ContainerAllocator2> & rhs)
{
  return lhs.current == rhs.current;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::real_robot_control::current_pub_<ContainerAllocator1> & lhs, const ::real_robot_control::current_pub_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace real_robot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::real_robot_control::current_pub_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::real_robot_control::current_pub_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::real_robot_control::current_pub_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::real_robot_control::current_pub_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::real_robot_control::current_pub_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::real_robot_control::current_pub_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::real_robot_control::current_pub_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca4d0ba43a70fe6e37b76accdbf3ef40";
  }

  static const char* value(const ::real_robot_control::current_pub_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca4d0ba43a70fe6eULL;
  static const uint64_t static_value2 = 0x37b76accdbf3ef40ULL;
};

template<class ContainerAllocator>
struct DataType< ::real_robot_control::current_pub_<ContainerAllocator> >
{
  static const char* value()
  {
    return "real_robot_control/current_pub";
  }

  static const char* value(const ::real_robot_control::current_pub_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::real_robot_control::current_pub_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 current\n"
;
  }

  static const char* value(const ::real_robot_control::current_pub_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::real_robot_control::current_pub_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct current_pub_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::real_robot_control::current_pub_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::real_robot_control::current_pub_<ContainerAllocator>& v)
  {
    s << indent << "current: ";
    Printer<double>::stream(s, indent + "  ", v.current);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REAL_ROBOT_CONTROL_MESSAGE_CURRENT_PUB_H
