// Generated by gencpp from file real_robot_control/gripper.msg
// DO NOT EDIT!


#ifndef REAL_ROBOT_CONTROL_MESSAGE_GRIPPER_H
#define REAL_ROBOT_CONTROL_MESSAGE_GRIPPER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace real_robot_control
{
template <class ContainerAllocator>
struct gripper_
{
  typedef gripper_<ContainerAllocator> Type;

  gripper_()
    : open(0.0)  {
    }
  gripper_(const ContainerAllocator& _alloc)
    : open(0.0)  {
  (void)_alloc;
    }



   typedef double _open_type;
  _open_type open;





  typedef boost::shared_ptr< ::real_robot_control::gripper_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::real_robot_control::gripper_<ContainerAllocator> const> ConstPtr;

}; // struct gripper_

typedef ::real_robot_control::gripper_<std::allocator<void> > gripper;

typedef boost::shared_ptr< ::real_robot_control::gripper > gripperPtr;
typedef boost::shared_ptr< ::real_robot_control::gripper const> gripperConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::real_robot_control::gripper_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::real_robot_control::gripper_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::real_robot_control::gripper_<ContainerAllocator1> & lhs, const ::real_robot_control::gripper_<ContainerAllocator2> & rhs)
{
  return lhs.open == rhs.open;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::real_robot_control::gripper_<ContainerAllocator1> & lhs, const ::real_robot_control::gripper_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace real_robot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::real_robot_control::gripper_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::real_robot_control::gripper_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::real_robot_control::gripper_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::real_robot_control::gripper_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::real_robot_control::gripper_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::real_robot_control::gripper_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::real_robot_control::gripper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1cd3c8c0899095b58f167c1f2be4d95a";
  }

  static const char* value(const ::real_robot_control::gripper_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1cd3c8c0899095b5ULL;
  static const uint64_t static_value2 = 0x8f167c1f2be4d95aULL;
};

template<class ContainerAllocator>
struct DataType< ::real_robot_control::gripper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "real_robot_control/gripper";
  }

  static const char* value(const ::real_robot_control::gripper_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::real_robot_control::gripper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 open\n"
;
  }

  static const char* value(const ::real_robot_control::gripper_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::real_robot_control::gripper_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.open);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gripper_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::real_robot_control::gripper_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::real_robot_control::gripper_<ContainerAllocator>& v)
  {
    s << indent << "open: ";
    Printer<double>::stream(s, indent + "  ", v.open);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REAL_ROBOT_CONTROL_MESSAGE_GRIPPER_H
