// Generated by gencpp from file real_robot_control/leftrobot.msg
// DO NOT EDIT!


#ifndef REAL_ROBOT_CONTROL_MESSAGE_LEFTROBOT_H
#define REAL_ROBOT_CONTROL_MESSAGE_LEFTROBOT_H

#include <ros/service_traits.h>


#include <real_robot_control/leftrobotRequest.h>
#include <real_robot_control/leftrobotResponse.h>


namespace real_robot_control
{

struct leftrobot
{

typedef leftrobotRequest Request;
typedef leftrobotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct leftrobot
} // namespace real_robot_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::real_robot_control::leftrobot > {
  static const char* value()
  {
    return "7b18929c222448a67fda0cd87f44304d";
  }

  static const char* value(const ::real_robot_control::leftrobot&) { return value(); }
};

template<>
struct DataType< ::real_robot_control::leftrobot > {
  static const char* value()
  {
    return "real_robot_control/leftrobot";
  }

  static const char* value(const ::real_robot_control::leftrobot&) { return value(); }
};


// service_traits::MD5Sum< ::real_robot_control::leftrobotRequest> should match
// service_traits::MD5Sum< ::real_robot_control::leftrobot >
template<>
struct MD5Sum< ::real_robot_control::leftrobotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::real_robot_control::leftrobot >::value();
  }
  static const char* value(const ::real_robot_control::leftrobotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::real_robot_control::leftrobotRequest> should match
// service_traits::DataType< ::real_robot_control::leftrobot >
template<>
struct DataType< ::real_robot_control::leftrobotRequest>
{
  static const char* value()
  {
    return DataType< ::real_robot_control::leftrobot >::value();
  }
  static const char* value(const ::real_robot_control::leftrobotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::real_robot_control::leftrobotResponse> should match
// service_traits::MD5Sum< ::real_robot_control::leftrobot >
template<>
struct MD5Sum< ::real_robot_control::leftrobotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::real_robot_control::leftrobot >::value();
  }
  static const char* value(const ::real_robot_control::leftrobotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::real_robot_control::leftrobotResponse> should match
// service_traits::DataType< ::real_robot_control::leftrobot >
template<>
struct DataType< ::real_robot_control::leftrobotResponse>
{
  static const char* value()
  {
    return DataType< ::real_robot_control::leftrobot >::value();
  }
  static const char* value(const ::real_robot_control::leftrobotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REAL_ROBOT_CONTROL_MESSAGE_LEFTROBOT_H
