// Generated by gencpp from file real_robot_control/leftrobotRequest.msg
// DO NOT EDIT!


#ifndef REAL_ROBOT_CONTROL_MESSAGE_LEFTROBOTREQUEST_H
#define REAL_ROBOT_CONTROL_MESSAGE_LEFTROBOTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace real_robot_control
{
template <class ContainerAllocator>
struct leftrobotRequest_
{
  typedef leftrobotRequest_<ContainerAllocator> Type;

  leftrobotRequest_()
    : num(0)  {
    }
  leftrobotRequest_(const ContainerAllocator& _alloc)
    : num(0)  {
  (void)_alloc;
    }



   typedef int32_t _num_type;
  _num_type num;





  typedef boost::shared_ptr< ::real_robot_control::leftrobotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::real_robot_control::leftrobotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct leftrobotRequest_

typedef ::real_robot_control::leftrobotRequest_<std::allocator<void> > leftrobotRequest;

typedef boost::shared_ptr< ::real_robot_control::leftrobotRequest > leftrobotRequestPtr;
typedef boost::shared_ptr< ::real_robot_control::leftrobotRequest const> leftrobotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::real_robot_control::leftrobotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::real_robot_control::leftrobotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::real_robot_control::leftrobotRequest_<ContainerAllocator1> & lhs, const ::real_robot_control::leftrobotRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::real_robot_control::leftrobotRequest_<ContainerAllocator1> & lhs, const ::real_robot_control::leftrobotRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace real_robot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::real_robot_control::leftrobotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::real_robot_control::leftrobotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::real_robot_control::leftrobotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::real_robot_control::leftrobotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::real_robot_control::leftrobotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::real_robot_control::leftrobotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::real_robot_control::leftrobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54b3c80efd6fae6e6ffff8a4b9facd69";
  }

  static const char* value(const ::real_robot_control::leftrobotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54b3c80efd6fae6eULL;
  static const uint64_t static_value2 = 0x6ffff8a4b9facd69ULL;
};

template<class ContainerAllocator>
struct DataType< ::real_robot_control::leftrobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "real_robot_control/leftrobotRequest";
  }

  static const char* value(const ::real_robot_control::leftrobotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::real_robot_control::leftrobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#目标值\n"
"int32 num\n"
;
  }

  static const char* value(const ::real_robot_control::leftrobotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::real_robot_control::leftrobotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct leftrobotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::real_robot_control::leftrobotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::real_robot_control::leftrobotRequest_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REAL_ROBOT_CONTROL_MESSAGE_LEFTROBOTREQUEST_H
