// Generated by gencpp from file real_robot_control/pose.msg
// DO NOT EDIT!


#ifndef REAL_ROBOT_CONTROL_MESSAGE_POSE_H
#define REAL_ROBOT_CONTROL_MESSAGE_POSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32MultiArray.h>

namespace real_robot_control
{
template <class ContainerAllocator>
struct pose_
{
  typedef pose_<ContainerAllocator> Type;

  pose_()
    : matrices()  {
    }
  pose_(const ContainerAllocator& _alloc)
    : matrices(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::std_msgs::Float32MultiArray_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::std_msgs::Float32MultiArray_<ContainerAllocator> >> _matrices_type;
  _matrices_type matrices;





  typedef boost::shared_ptr< ::real_robot_control::pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::real_robot_control::pose_<ContainerAllocator> const> ConstPtr;

}; // struct pose_

typedef ::real_robot_control::pose_<std::allocator<void> > pose;

typedef boost::shared_ptr< ::real_robot_control::pose > posePtr;
typedef boost::shared_ptr< ::real_robot_control::pose const> poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::real_robot_control::pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::real_robot_control::pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::real_robot_control::pose_<ContainerAllocator1> & lhs, const ::real_robot_control::pose_<ContainerAllocator2> & rhs)
{
  return lhs.matrices == rhs.matrices;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::real_robot_control::pose_<ContainerAllocator1> & lhs, const ::real_robot_control::pose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace real_robot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::real_robot_control::pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::real_robot_control::pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::real_robot_control::pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::real_robot_control::pose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::real_robot_control::pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::real_robot_control::pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::real_robot_control::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "04c3645e7964b08a28c0477b52d83e5b";
  }

  static const char* value(const ::real_robot_control::pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x04c3645e7964b08aULL;
  static const uint64_t static_value2 = 0x28c0477b52d83e5bULL;
};

template<class ContainerAllocator>
struct DataType< ::real_robot_control::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "real_robot_control/pose";
  }

  static const char* value(const ::real_robot_control::pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::real_robot_control::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32MultiArray[] matrices\n"
"================================================================================\n"
"MSG: std_msgs/Float32MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float32[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::real_robot_control::pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::real_robot_control::pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.matrices);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::real_robot_control::pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::real_robot_control::pose_<ContainerAllocator>& v)
  {
    s << indent << "matrices[]" << std::endl;
    for (size_t i = 0; i < v.matrices.size(); ++i)
    {
      s << indent << "  matrices[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "    ", v.matrices[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // REAL_ROBOT_CONTROL_MESSAGE_POSE_H
