// Generated by gencpp from file real_robot_control/screwsrv.msg
// DO NOT EDIT!


#ifndef REAL_ROBOT_CONTROL_MESSAGE_SCREWSRV_H
#define REAL_ROBOT_CONTROL_MESSAGE_SCREWSRV_H

#include <ros/service_traits.h>


#include <real_robot_control/screwsrvRequest.h>
#include <real_robot_control/screwsrvResponse.h>


namespace real_robot_control
{

struct screwsrv
{

typedef screwsrvRequest Request;
typedef screwsrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct screwsrv
} // namespace real_robot_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::real_robot_control::screwsrv > {
  static const char* value()
  {
    return "7b18929c222448a67fda0cd87f44304d";
  }

  static const char* value(const ::real_robot_control::screwsrv&) { return value(); }
};

template<>
struct DataType< ::real_robot_control::screwsrv > {
  static const char* value()
  {
    return "real_robot_control/screwsrv";
  }

  static const char* value(const ::real_robot_control::screwsrv&) { return value(); }
};


// service_traits::MD5Sum< ::real_robot_control::screwsrvRequest> should match
// service_traits::MD5Sum< ::real_robot_control::screwsrv >
template<>
struct MD5Sum< ::real_robot_control::screwsrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::real_robot_control::screwsrv >::value();
  }
  static const char* value(const ::real_robot_control::screwsrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::real_robot_control::screwsrvRequest> should match
// service_traits::DataType< ::real_robot_control::screwsrv >
template<>
struct DataType< ::real_robot_control::screwsrvRequest>
{
  static const char* value()
  {
    return DataType< ::real_robot_control::screwsrv >::value();
  }
  static const char* value(const ::real_robot_control::screwsrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::real_robot_control::screwsrvResponse> should match
// service_traits::MD5Sum< ::real_robot_control::screwsrv >
template<>
struct MD5Sum< ::real_robot_control::screwsrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::real_robot_control::screwsrv >::value();
  }
  static const char* value(const ::real_robot_control::screwsrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::real_robot_control::screwsrvResponse> should match
// service_traits::DataType< ::real_robot_control::screwsrv >
template<>
struct DataType< ::real_robot_control::screwsrvResponse>
{
  static const char* value()
  {
    return DataType< ::real_robot_control::screwsrv >::value();
  }
  static const char* value(const ::real_robot_control::screwsrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REAL_ROBOT_CONTROL_MESSAGE_SCREWSRV_H
