controller_list:
  - name: arm
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - l_j1
      - l_j2
      - l_j3
      - l_j4
      - l_j5
      - l_j6
      - r_j1
      - r_j2
      - r_j3
      - r_j4
      - r_j5
      - r_j6
  - name: gripper
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - l_p1
      - l_p2
  - name: screw_tool
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - r_c1
      - r_p1
      - r_p2