// Auto-generated. Do not edit!

// (in-package real_robot_control.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class screwFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.screw_status = null;
    }
    else {
      if (initObj.hasOwnProperty('screw_status')) {
        this.screw_status = initObj.screw_status
      }
      else {
        this.screw_status = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type screwFeedback
    // Serialize message field [screw_status]
    bufferOffset = _serializer.float64(obj.screw_status, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type screwFeedback
    let len;
    let data = new screwFeedback(null);
    // Deserialize message field [screw_status]
    data.screw_status = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'real_robot_control/screwFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e3afaebb6a3462d8877452e53c10c331';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #连续反馈
    float64 screw_status
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new screwFeedback(null);
    if (msg.screw_status !== undefined) {
      resolved.screw_status = msg.screw_status;
    }
    else {
      resolved.screw_status = 0.0
    }

    return resolved;
    }
};

module.exports = screwFeedback;
