# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from real_robot_control/ori_adj_rec.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ori_adj_rec(genpy.Message):
  _md5sum = "41fd7db046eaccfb5112edd2ddb827ba"
  _type = "real_robot_control/ori_adj_rec"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 phi
int32 point_num
int32 record_item
float64 Rx
float64 Ry
float64 Rz"""
  __slots__ = ['phi','point_num','record_item','Rx','Ry','Rz']
  _slot_types = ['int32','int32','int32','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       phi,point_num,record_item,Rx,Ry,Rz

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ori_adj_rec, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.phi is None:
        self.phi = 0
      if self.point_num is None:
        self.point_num = 0
      if self.record_item is None:
        self.record_item = 0
      if self.Rx is None:
        self.Rx = 0.
      if self.Ry is None:
        self.Ry = 0.
      if self.Rz is None:
        self.Rz = 0.
    else:
      self.phi = 0
      self.point_num = 0
      self.record_item = 0
      self.Rx = 0.
      self.Ry = 0.
      self.Rz = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3i3d().pack(_x.phi, _x.point_num, _x.record_item, _x.Rx, _x.Ry, _x.Rz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.phi, _x.point_num, _x.record_item, _x.Rx, _x.Ry, _x.Rz,) = _get_struct_3i3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3i3d().pack(_x.phi, _x.point_num, _x.record_item, _x.Rx, _x.Ry, _x.Rz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.phi, _x.point_num, _x.record_item, _x.Rx, _x.Ry, _x.Rz,) = _get_struct_3i3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3i3d = None
def _get_struct_3i3d():
    global _struct_3i3d
    if _struct_3i3d is None:
        _struct_3i3d = struct.Struct("<3i3d")
    return _struct_3i3d
